# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jakub Dorda
email: jakub.dorda@gmail.com
linkedin: jakub-dorda-0757b0144
github: jakdor
facebook: jakub.dorda
medium: jakdor00
description: I'm Android/iOS enthusiast & Xamarin developer. I'm student at Wroclaw University of Science and Technology. I'm currently working for Blue Veery GmbH. I'm astrophysics fan, and astrophotographer by night.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jakdor.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
